'use client';

import { useMemo, useState } from 'react';
import { balance, documentTotals, downloadCsv, initials, leadValue, money, normaliseStage, received, shortDate, today, uid } from '@/lib/client/business';
import { Avatar, Button, Empty, Field, Metric, Modal, PageHeader, Search } from '../ui';

export function Clients({ data, onEdit, openNew, onNewTask }) {
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('all');
  const clients = useMemo(() => data.leads.filter(lead => normaliseStage(lead.stage) === 'Converted / Payment Done').filter(lead => {
    const hay = [lead.name, lead.company, lead.phone, lead.city, lead.service].join(' ').toLowerCase();
    const task = data.tasks.find(item => item.leadId === lead.id);
    const matchesFilter = filter === 'all' || filter === 'due' ? balance(lead) > 0 : filter === 'complete' ? task?.status === 'Completed' : task?.status !== 'Completed';
    return (!query || hay.includes(query.toLowerCase())) && (filter === 'all' || matchesFilter);
  }), [data.leads, data.tasks, query, filter]);
  const allClients = data.leads.filter(lead => normaliseStage(lead.stage) === 'Converted / Payment Done');
  const active = allClients.filter(lead => data.tasks.some(task => task.leadId === lead.id && task.status !== 'Completed')).length;
  return <section className="page active" id="clients">
    <div className="vlos-pagebar"><div><div className="vlos-eyebrow">Service Delivery</div><h1 className="vlos-page-title">Clients</h1></div><div className="actions"><button className="btn dark vlos-team-add-client-allowed" type="button" onClick={openNew}>＋ Add Client</button></div></div>
    <div className="vlos-client-metrics"><div className="vlos-client-metric"><span>Total clients</span><strong>{allClients.length}</strong></div><div className="vlos-client-metric blue"><span>Active work</span><strong>{active}</strong></div><div className="vlos-client-metric red"><span>Payment due</span><strong>{allClients.filter(lead => balance(lead) > 0).length}</strong></div><div className="vlos-client-metric green"><span>Work completed</span><strong>{allClients.filter(lead => data.tasks.some(task => task.leadId === lead.id && task.status === 'Completed')).length}</strong></div></div>
    <div className="vlos-client-toolbar"><div className="search"><input placeholder="Search client, business, phone or service" value={query} onChange={event => setQuery(event.target.value)} /></div><select className="filter" value={filter} onChange={event => setFilter(event.target.value)}><option value="all">All clients</option><option value="active">Active work</option><option value="due">Payment due</option><option value="complete">Completed work</option></select></div>
    <div className="vlos-client-grid">{clients.length ? clients.map(lead => { const tasks = data.tasks.filter(item => item.leadId === lead.id); const done = tasks.filter(task => task.status === 'Completed').length; const open = tasks.length - done; const status = balance(lead) > 0 ? ['due', 'Payment due'] : tasks.length && tasks.every(task => task.status === 'Completed') ? ['complete', 'Completed'] : ['active', 'Active work']; return <article className="vlos-client-card" key={lead.id}><div className="vlos-client-top"><div className="vlos-client-logo">{lead.clientLogo ? <img src={lead.clientLogo} alt="" /> : initials(lead.company || lead.name)}</div><div><div className="vlos-client-name">{lead.company || lead.name || lead.phone}</div><div className="vlos-client-service">{lead.service || 'Service client'}</div></div><span className={`vlos-client-status ${status[0]}`}>{status[1]}</span></div><div className="vlos-client-info">{lead.name || 'Contact not added'} · {lead.phone || 'No phone'}<br />{lead.email || 'No email'}</div><div className="vlos-client-kpis"><div className="vlos-client-kpi"><strong>{tasks.length}</strong><span>Tasks</span></div><div className="vlos-client-kpi"><strong>{open}</strong><span>Open</span></div><div className="vlos-client-kpi"><strong>{done}</strong><span>Done</span></div></div><div className="vlos-client-actions"><button className="btn" type="button" onClick={() => onEdit(lead)}>View Details</button><button className="btn dark" type="button" onClick={() => onNewTask(lead)}>＋ Task</button></div></article>; }) : <Empty>No clients yet. Add a client or convert a sales lead.</Empty>}</div>
  </section>;
}

export function FinanceEditor({ onClose, onSave }) {
  const [form, setForm] = useState({ type: 'expense', amount: '', category: 'Meta Ads', date: today(), description: '' });
  const set = (key, value) => setForm(current => ({ ...current, [key]: value }));
  return <Modal title="Add money entry" subtitle="Record direct income or an investment" onClose={onClose} footer={<><span /><div><Button onClick={onClose}>Cancel</Button><Button variant="primary" onClick={() => Number(form.amount) > 0 && onSave({ ...form, id: uid('finance'), amount: Number(form.amount), description: form.description || form.category })}>Save entry</Button></div></>}><div className="form form-grid"><Field label="Entry type"><select value={form.type} onChange={event => set('type', event.target.value)}><option value="expense">Investment / expense</option><option value="income">Direct income</option></select></Field><Field label="Amount"><input type="number" min="0" value={form.amount} onChange={event => set('amount', event.target.value)} autoFocus /></Field><Field label="Category"><select value={form.category} onChange={event => set('category', event.target.value)}><option>Meta Ads</option><option>Google Ads</option><option>Software</option><option>Salary</option><option>Operations</option><option>Travel</option><option>Client Payment</option><option>Other</option></select></Field><Field label="Date"><input type="date" value={form.date} onChange={event => set('date', event.target.value)} /></Field><Field label="Description" wide><input value={form.description} onChange={event => set('description', event.target.value)} /></Field></div></Modal>;
}

export function Finance({ data, openNew, onDelete }) {
  const unlinkedQuotes = data.documents.filter(doc => ['quotation', 'estimate', 'proforma'].includes(doc.kind) && doc.status !== 'cancelled' && !doc.leadId);
  const unlinkedInvoices = data.documents.filter(doc => ['invoice', 'sales_invoice'].includes(doc.kind) && doc.status !== 'cancelled' && !doc.leadId);
  const quote = data.leads.reduce((sum, lead) => sum + Number(lead.quote || 0), 0) + unlinkedQuotes.reduce((sum, doc) => sum + documentTotals(doc).grand, 0);
  const booked = data.leads.filter(lead => normaliseStage(lead.stage) === 'Converted / Payment Done').reduce((sum, lead) => sum + leadValue(lead), 0) + unlinkedInvoices.reduce((sum, doc) => sum + documentTotals(doc).grand, 0);
  const leadIncome = data.leads.reduce((sum, lead) => sum + received(lead), 0);
  const billingIncome = unlinkedInvoices.reduce((sum, doc) => sum + Number(doc.paid || 0), 0);
  const direct = data.finance.filter(item => item.type === 'income').reduce((sum, item) => sum + Number(item.amount || 0), 0);
  const investment = data.finance.filter(item => item.type === 'expense').reduce((sum, item) => sum + Number(item.amount || 0), 0);
  const collected = leadIncome + billingIncome + direct;
  const transactions = [...data.finance.map(item => ({ ...item, locked: false })), ...data.leads.filter(lead => received(lead) > 0).map(lead => ({ id: `lead_${lead.id}`, type: 'income', amount: received(lead), category: 'Client payment', date: lead.paymentDate || lead.lastUpdatedAt || lead.createdAt, description: lead.company || lead.name, locked: true })), ...unlinkedInvoices.filter(doc => Number(doc.paid || 0) > 0).map(doc => ({ id: `bill_${doc.id}`, type: 'income', amount: Number(doc.paid || 0), category: `Invoice #${doc.number}`, date: doc.date, description: doc.clientName, locked: true }))].sort((a, b) => String(b.date || '').localeCompare(String(a.date || '')));
  const months = Array.from({ length: 6 }, (_, index) => { const date = new Date(); date.setMonth(date.getMonth() - (5 - index), 1); const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`; const rows = transactions.filter(item => String(item.date || '').slice(0, 7) === key); return { key, label: date.toLocaleDateString('en-IN', { month: 'short' }), income: rows.filter(item => item.type === 'income').reduce((sum, item) => sum + Number(item.amount || 0), 0), expense: rows.filter(item => item.type === 'expense').reduce((sum, item) => sum + Number(item.amount || 0), 0) }; });
  const chartMax = Math.max(1, ...months.flatMap(item => [item.income, item.expense]));
  return <section className="page active" id="finance">
    <div className="softwarebar"><div className="v68-page-heading"><span>Money overview</span><h1>Finance</h1></div><div className="actions"><button className="btn" type="button" onClick={() => downloadCsv(`visitinglink-finance-${today()}.csv`, [['Type', 'Amount', 'Category', 'Date', 'Description'], ...transactions.map(item => [item.type, item.amount, item.category, item.date, item.description])])}>Export</button><button className="btn dark" type="button" onClick={openNew}>Add entry</button></div></div>
    <div className="grid finmetrics"><Metric label="Quoted" value={money(quote)} /><Metric label="Booked" value={money(booked)} /><Metric label="Collected" value={money(collected)} /><Metric label="Outstanding" value={money(Math.max(0, booked - leadIncome - billingIncome))} /><Metric label="Investment" value={money(investment)} /><Metric label="Net cash" value={money(collected - investment)} /></div>
    <div className="grid finlayout"><div className="card"><div className="cardhead"><div><div className="cardtitle">Six-month movement</div><div className="cardsub">Collected versus investment</div></div></div><div className="chart">{months.map(item => <div className="month" key={item.key}><div className="bar" title={`Collected ${money(item.income)}`} style={{ height: `${Math.max(3, item.income / chartMax * 100)}%`, background: '#168a48' }} /><div className="bar" title={`Investment ${money(item.expense)}`} style={{ height: `${Math.max(3, item.expense / chartMax * 100)}%`, background: '#d92d20' }} /><span className="mlabel">{item.label}</span></div>)}</div></div><div className="card"><div className="cardhead"><div><div className="cardtitle">Recent money activity</div><div className="cardsub">Lead payments and manual entries</div></div></div><div className="trans">{transactions.length ? transactions.slice(0, 9).map(item => <div className="tx" key={item.id}><span className={`txicon ${item.type}`}>{item.type === 'income' ? '↓' : '↑'}</span><span><strong>{item.description}</strong><p>{item.category} · {shortDate(item.date)}</p></span><strong className={`amount ${item.type}`}>{item.type === 'income' ? '+' : '−'}{money(item.amount)}</strong>{!item.locked ? <button className="btn" type="button" onClick={() => onDelete(item)}>×</button> : <span />}</div>) : <Empty>No money activity yet.</Empty>}</div></div></div>
  </section>;
}

export function Collection({ data, onEdit, onBill, onPayment }) {
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('all');
  const [owner, setOwner] = useState('');
  const leadDues = data.leads.filter(lead => normaliseStage(lead.stage) === 'Converted / Payment Done' && balance(lead) > 0);
  const invoiceDues = data.documents.filter(doc => ['invoice', 'sales_invoice'].includes(doc.kind) && doc.status !== 'cancelled' && !doc.leadId && documentTotals(doc).grand > Number(doc.paid || 0));
  const todayKey = today();
  const overdue = leadDues.filter(lead => lead.collectionDate && lead.collectionDate < todayKey);
  const dueToday = leadDues.filter(lead => lead.collectionDate === todayKey);
  const upcoming = leadDues.filter(lead => !lead.collectionDate || lead.collectionDate > todayKey);
  const invoiceDue = doc => Math.max(0, documentTotals(doc).grand - Number(doc.paid || 0));
  const invoiceOverdue = invoiceDues.filter(doc => doc.dueDate && doc.dueDate < todayKey);
  const invoiceToday = invoiceDues.filter(doc => doc.dueDate === todayKey);
  const invoiceUpcoming = invoiceDues.filter(doc => !doc.dueDate || doc.dueDate > todayKey);
  const total = leadDues.reduce((sum, lead) => sum + balance(lead), 0) + invoiceDues.reduce((sum, doc) => sum + invoiceDue(doc), 0);
  const allCount = leadDues.length + invoiceDues.length;
  const timingOf = date => date && date < todayKey ? 'overdue' : date === todayKey ? 'today' : date ? 'upcoming' : 'nodate';
  const matches = (item, date, text, itemOwner = '') => (!query || text.toLowerCase().includes(query.toLowerCase())) && (filter === 'all' || timingOf(date) === filter) && (!owner || itemOwner === owner);
  const visibleLeads = leadDues.filter(lead => matches(lead, lead.collectionDate, [lead.company, lead.name, lead.phone, lead.service, lead.collectionNote].join(' '), lead.collectionOwner));
  const visibleInvoices = invoiceDues.filter(doc => matches(doc, doc.dueDate, [doc.clientName, doc.clientPhone, doc.number, ...(doc.items || []).map(item => item.name)].join(' ')));
  return <section className="page active" id="collection">
    <div className="vlos-pagebar"><div><div className="vlos-eyebrow">Payment Recovery</div><h1 className="vlos-page-title">Collection</h1></div><div className="actions"><button className="btn" type="button" onClick={() => window.Notification?.requestPermission?.()}>Enable Notifications</button><button className="btn dark" type="button" onClick={() => { setQuery(''); setFilter('all'); setOwner(''); }}>Refresh</button></div></div>
    <div className="grid vl-collection-kpis"><Metric label="Total receivable" value={money(total)} /><Metric label="Overdue" value={money(overdue.reduce((sum, lead) => sum + balance(lead), 0) + invoiceOverdue.reduce((sum, doc) => sum + invoiceDue(doc), 0))} /><Metric label="Due today" value={money(dueToday.reduce((sum, lead) => sum + balance(lead), 0) + invoiceToday.reduce((sum, doc) => sum + invoiceDue(doc), 0))} /><Metric label="Upcoming" value={money(upcoming.reduce((sum, lead) => sum + balance(lead), 0) + invoiceUpcoming.reduce((sum, doc) => sum + invoiceDue(doc), 0))} /></div>
    <div className="toolbar vl-collection-toolbar"><div className="search"><input placeholder="Search client, phone, service or recovery owner" value={query} onChange={event => setQuery(event.target.value)} /></div><select className="filter" value={filter} onChange={event => setFilter(event.target.value)}><option value="all">All receivables</option><option value="overdue">Overdue</option><option value="today">Due today</option><option value="upcoming">Upcoming</option><option value="nodate">Date not set</option></select><select className="filter" value={owner} onChange={event => setOwner(event.target.value)}><option value="">All recovery owners</option>{data.team.map(member => <option key={member.id} value={member.id}>{member.name}</option>)}</select></div>
    <div className="vl-collection-grid">{visibleLeads.map(lead => { const timing = timingOf(lead.collectionDate); return <article className={`vl-collection-card ${timing}`} key={lead.id}><div className="vl-collection-top"><div className="vl-collection-avatar">{initials(lead.company || lead.name)}</div><div className="vl-collection-copy"><strong>{lead.company || lead.name}</strong><span>{lead.phone} · {lead.service}</span></div><div className="vl-collection-balance">{money(balance(lead))}</div></div><div className="vl-collection-date"><span className={`vl-due-pill ${timing}`}>{timing === 'overdue' ? 'Overdue' : timing === 'today' ? 'Due today' : timing === 'nodate' ? 'Date not set' : 'Upcoming'}</span><strong>{shortDate(lead.collectionDate || lead.follow)}</strong></div><div className="vl-collection-note">{lead.collectionNote || lead.notes || 'No collection note added.'}</div><div className="vl-collection-actions">{lead.phone && <a className="btn" href={`tel:${lead.phone}`}>Call</a>}<button className="btn dark" type="button" onClick={() => onEdit(lead)}>Update payment</button></div></article>; })}{visibleInvoices.map(doc => { const timing = timingOf(doc.dueDate); return <article className={`vl-collection-card ${timing}`} key={doc.id}><div className="vl-collection-top"><div className="vl-collection-avatar">{initials(doc.clientName)}</div><div className="vl-collection-copy"><strong>{doc.clientName || 'Client'}</strong><span>Invoice #{doc.number} · {(doc.items || []).map(item => item.name).filter(Boolean).join(' · ') || 'Billing'}</span></div><div className="vl-collection-balance">{money(invoiceDue(doc))}</div></div><div className="vl-collection-date"><span className={`vl-due-pill ${timing}`}>{timing === 'overdue' ? 'Overdue' : timing === 'today' ? 'Due today' : timing === 'nodate' ? 'Date not set' : 'Upcoming'}</span><strong>{shortDate(doc.dueDate)}</strong></div><div className="vl-collection-note">Total {money(documentTotals(doc).grand)} · Collected {money(doc.paid)} · Pending {money(invoiceDue(doc))}</div><div className="vl-collection-actions"><button className="btn" type="button" onClick={() => onBill(doc)}>Open bill</button><button className="btn dark" type="button" onClick={() => onPayment(doc)}>Record payment</button></div></article>; })}{!visibleLeads.length && !visibleInvoices.length && <Empty>{allCount ? 'No collections match this view.' : 'No pending collections.'}</Empty>}</div>
  </section>;
}
